/* ===============================================================
   PROJECTS DATA
   Structured content for each project detail page. Sourced directly
   from the project cards on the Projects page (same copy, same media),
   just organized for the individual project pages.
   =============================================================== */

var PROJECTS_ORDER = ["cooling-sim", "cooling-loop", "drivetrain", "maple-structures", "nose-gear", "arming-housing", "red-lamp", "planet-shafts", "pg-marketing", "face-tracking-robot"];

var PROJECTS = {
  "cooling-sim": {
    id: "cooling-sim",
    number: "01",
    title: `Dual Cooling Loop System Simulation`,
    category: "fsae",
    categoryLabel: `Formula SAE`,
    org: `University of Toronto Formula SAE Racing`,
    date: `April 2026 — May 2026`,
    award: null,
    overview: `Developed a physics-based MATLAB/Simulink thermal model of a dual-inverter cooling loop to predict motor temperatures under endurance race conditions, digitizing the Fischer motor's power-efficiency map into a high-resolution lookup table to establish the system's thermal boundary condition. The simulated endurance run returned a mean motor efficiency of 95.84% (ranging 86.09%–97.97%), corresponding to an average thermal loss of ~5.5 kW that the cooling system was sized to reject. The model was validated against historical endurance-run telemetry and used to evaluate cooling performance across varying vehicle speeds and thermal loads.`,
    keyFeatures: [
      `Developed a MATLAB/Simulink thermal model of the dual-inverter cooling loop to predict motor temperatures under endurance race operating conditions.`,
      `Digitized the Fischer motor's power-efficiency map into a high-resolution lookup table using automated MATLAB tools, then integrated it into the Simulink vehicle model for continuous efficiency evaluation through a simulated endurance event.`,
      `Calculated electrical losses using P_loss = P_input(1 − η), yielding a mean motor efficiency of 95.84% (min 86.09%, max 97.97%) and an average thermal loss of ~5.5 kW — the heat-removal target used to size the cooling system.`,
      `Modeled heat transfer throughout the cooling circuit, including heat addition from powertrain components and heat rejection through the radiator.`,
    ],
    designProcess: [
      `Used historical endurance run telemetry and component data to provide realistic operating inputs and thermal loading conditions.`,
      `Validated the cooling loop model by comparing simulated motor temperatures against measured endurance run temperature data.`,
      `Evaluated cooling system performance across varying vehicle speeds and thermal loads to assess temperature regulation capability.`,
      `Established a simulation framework that can be used to analyze the impact of future cooling system modifications on motor thermal performance.`,
    ],
    techUsed: ["Simulink", "MATLAB", "Thermal Management", "Simulation"],
    media: [
      { type: "image", src: "https://i.imgur.com/8qLKQCk.png", alt: `cooling sim` },
      { type: "image", src: "https://i.imgur.com/SCPSP5B.png", alt: `motor temp` },
    ],
  },
  "cooling-loop": {
    id: "cooling-loop",
    number: "02",
    title: `Dual Series Cooling Loop`,
    category: "fsae",
    categoryLabel: `Formula SAE`,
    org: `University of Toronto Formula SAE Racing`,
    date: `2025 — 2026`,
    award: null,
    overview: `Designed, built, and tested a full dual cooling loop system for an electric powertrain, integrating CAD design, fabrication, and real-world validation. The project included tubing assembly, sensor integration, pump priming, and bench testing to ensure reliable thermal performance under race conditions.`,
    keyFeatures: [
      `A dual-loop architecture with independent cooling loops for left and right sides of the vehicle.`,
      `This design enhances reliability and simplifies plumbing by minimizing long coolant runs.`,
      `Key considerations: Radiator placement and component ordering within the cooling loop`,
      `The rear was identified by the aerodynamics team as the optimal location for the radiator, benefiting from high-energy airflow while preserving front aerodynamics.`,
    ],
    designProcess: [
      `Performed multiple bench tests to evaluate cooling system performance, verify component operation, and troubleshoot issues prior to vehicle deployment.`,
      `Manufactured and assembled the physical cooling system by cutting and routing coolant tubing, installing sensors, fittings, pumps, and other cooling components.`,
      `Conducted cooling loop integration and commissioning activities, including system priming, leak checks, and flow verification.`,
      `Collaborated with team members to optimize cooling loop packaging, assembly procedures, and overall system reliability for endurance competition conditions.`,
      `Components are ordered to prioritize cooling of the inverter, which is temperature-sensitive and positioned downstream of the radiator: Pump → Radiator → Inverter → Motor cooling jackets (in series).`,
      `The pump's placement before the radiator improves reliability by maintaining positive pressure at the pump inlet, reducing cavitation risk.`,
    ],
    techUsed: ["SolidWorks", "Thermal Management", "Manufacturing"],
    media: [
      { type: "image", src: "https://i.imgur.com/JLfQIhv.png", alt: `cooling loop render` },
      { type: "image", src: "https://i.imgur.com/I6R2xE2.jpeg", alt: `cooling loop` },
      { type: "video", src: "https://i.imgur.com/BbGiFTU.mp4" },
    ],
  },
  "drivetrain": {
    id: "drivetrain",
    number: "03",
    title: `UT26 Drivetrain System`,
    category: "fsae",
    categoryLabel: `Formula SAE`,
    org: `University of Toronto Formula SAE Racing`,
    date: `2025 — 2026`,
    award: null,
    overview: `Contributed to the design, manufacturing, and assembly of the UT26 in-hub AWD drivetrain system, engineered against corner-level targets of <40 kg mass, <0.25 kg·m² moment of inertia, and <3 h assembly time, ultimately achieving a 22.304 kg unsprung mass and 0.197 kg·m² mass moment of inertia. Supported integration of motors, gearbox components, and drivetrain hardware, including FEA-validated components such as the inboard motor mount (9.24 MPa max von Mises stress, safety factor >15). The project involved hands-on manufacturing, fixture design, and assembly process development to improve reliability and ease of installation.`,
    keyFeatures: [
      `Designed and manufactured an assembly jig to facilitate safe and accurate rotor installation in permanent magnet motors, addressing strong magnetic attraction forces between rotor and stator to ensure proper alignment during assembly.`,
      `Assisted in the assembly and integration of the drivetrain system, including motors, gearbox components, and supporting hardware, engineered to corner-level targets of &lt;40 kg mass and &lt;0.25 kg·m² moment of inertia — achieving 22.304 kg unsprung mass and 0.197 kg·m² mass moment of inertia in the final design.`,
      `Machined drivetrain components such as inboard motor mounts, planet shafts, and retainers to meet design specifications and assembly requirements, including the inboard motor mount validated by FEA to a maximum von Mises stress of 9.24 MPa and a safety factor greater than 15.`,
    ],
    designProcess: [
      `Participated in gearbox assembly and verification, ensuring proper fitment and alignment of drivetrain components across all four identical corner assemblies.`,
      `Worked with team members to troubleshoot assembly challenges and develop practical solutions to improve manufacturing and integration processes.`,
      `Supported the transition from CAD designs to physical components through machining, fabrication, and hands-on assembly.`,
    ],
    techUsed: ["SolidWorks", "Machining", "Hydraulic Pressure Press", "Gearbox", "Manufacturing"],
    media: [
      { type: "image", src: "https://i.imgur.com/KEhkIMK.jpeg", alt: `drivetrain render` },
      { type: "image", src: "https://i.imgur.com/7yG87nk.jpeg", alt: `drivetrain` },
      { type: "image", src: "https://i.imgur.com/kMlO5JT.jpeg", alt: `drivetrain` },
      { type: "image", src: "https://i.imgur.com/DMUPH1I.jpeg", alt: `drivetrain` },
      { type: "image", src: "https://i.imgur.com/FmMC2kx.jpeg", alt: `drivetrain` },
    ],
  },
  "maple-structures": {
    id: "maple-structures",
    number: "04",
    title: `UT26 MAPLE — Structures`,
    category: "aero",
    categoryLabel: `Aerospace / UAS`,
    org: `University of Toronto Aerospace Team — UAS`,
    date: `2025 — 2026`,
    award: null,
    overview: `Worked on the structures team for a UAS aircraft, responsible for manufacturing and assembly of the fuselage and landing gear systems. This included fabrication planning, composite integration, and hands-on assembly of airframe components to ensure structural integrity and flight readiness.`,
    keyFeatures: [
      `Worked on the UAS structures team responsible for the design, manufacturing, and assembly of the aircraft fuselage and landing gear systems.`,
      `Created laser-cut templates and fabrication guides to support accurate and repeatable fuselage construction processes.`,
      `Built and assembled the fuselage structure, including alignment, bonding, and reinforcement of airframe components.`,
    ],
    designProcess: [
      `Applied Monokote covering to the fuselage to improve aerodynamic finish and structural surface protection.`,
      `Cut, drilled, and prepared carbon fibre tubes for structural use while maintaining dimensional accuracy and material integrity.`,
      `Installed and integrated landing gear systems into the airframe, ensuring secure mounting and proper load distribution during landing conditions.`,
    ],
    techUsed: ["SolidWorks", "3D Printing", "Lasercutting", "Manufacture", "Aircraft Construction", "AutoCAD"],
    media: [
      { type: "image", src: "https://i.imgur.com/nBqKiDG.jpeg", alt: `UAS structures` },
      { type: "video", src: "https://i.imgur.com/V2GeKK2.mp4" },
      { type: "image", src: "https://i.imgur.com/e1Jl9mT.jpeg", alt: `UAS structures` },
      { type: "image", src: "https://i.imgur.com/NxiYCGL.jpeg", alt: `UAS structures` },
      { type: "image", src: "https://i.imgur.com/Uuju7Zj.jpeg", alt: `UAS structures` },
    ],
  },
  "nose-gear": {
    id: "nose-gear",
    number: "05",
    title: `UT26 Nose Landing Gear Integration`,
    category: "aero",
    categoryLabel: `Aerospace / UAS`,
    org: `University of Toronto Aerospace Team — UAS`,
    date: `May 2026`,
    award: null,
    overview: `Redesigned the nose landing gear system to convert it from a fuselage-integrated structure into a modular, independent subassembly to improve maintainability and manufacturability. This redesign significantly simplified maintenance procedures and reduced system integration and repair complexity.`,
    keyFeatures: [
      `Redesigned and integrated the nose landing gear system to improve maintainability, manufacturability, and assembly efficiency.`,
      `Converted the landing gear from a fuselage-dependent installation into a modular subassembly, significantly reducing maintenance, replacement, and aircraft turnaround time.`,
      `Redesigned critical mounting and interface components to enable independent fabrication, testing, and installation of the landing gear assembly.`,
      `Developed a modular architecture that simplified repairs and future design iterations, reducing integration complexity during aircraft assembly.`,
    ],
    designProcess: [
      `Manufactured and assembled the housing using additive manufacturing (3D printing), performing hands-on installation and fitment verification on the aircraft.`,
      `Iterated the design through multiple development cycles, progressing to Version 2 based on testing feedback, manufacturability considerations, and cross-team requirements.`,
      `Collaborated with avionics, structures, and manufacturing subteams to ensure compatibility with aircraft systems and streamline integration.`,
    ],
    techUsed: ["SolidWorks", "3D Printing", "Mechanical Design"],
    media: [
      { type: "image", src: "https://i.imgur.com/erKFIL5.png", alt: `nose landing gear` },
      { type: "video", src: "https://i.imgur.com/S9GidPP.mp4" },
      { type: "video", src: "https://i.imgur.com/0AzJEpz.mp4" },
    ],
  },
  "arming-housing": {
    id: "arming-housing",
    number: "06",
    title: `UT26 MAPLE — Arming Housing Design`,
    category: "aero",
    categoryLabel: `Aerospace / UAS`,
    org: `University of Toronto Aerospace Team — UAS`,
    date: `Mar 2026`,
    award: null,
    overview: `Designed and manufactured a modular arming housing system for a UAS platform, enabling safe and efficient electrical system activation and integration. The design was 3D printed and iteratively improved through multiple design cycles in collaboration with other subteams.`,
    keyFeatures: [
      `Designed and CAD-modeled a custom arming housing assembly for the UAS electrical system, ensuring secure integration with the airframe and accessibility during pre-flight operations.`,
      `Manufactured and assembled the housing using additive manufacturing (3D printing), performing hands-on installation and fitment verification on the aircraft.`,
    ],
    designProcess: [
      `Iterated the design through multiple development cycles, progressing to Version 2 based on testing feedback, manufacturability considerations, and cross-team requirements.`,
      `Collaborated with avionics subteams to ensure compatibility with aircraft systems and streamline integration.`,
    ],
    techUsed: ["SolidWorks", "3D Printing", "Mechanical Design"],
    media: [
      { type: "image", src: "https://i.imgur.com/7kMY9MU.png", alt: `arming housing` },
      { type: "image", src: "https://i.imgur.com/jWDbH4I.jpeg", alt: `arming housing` },
      { type: "image", src: "https://i.imgur.com/u8x3Kvi.jpeg", alt: `arming housing` },
    ],
  },
  "red-lamp": {
    id: "red-lamp",
    number: "07",
    title: `Red Lamp — Companion Robot`,
    category: "other",
    categoryLabel: `Hackathons & Other`,
    org: `UofTHacks 13`,
    date: `Jan 2026`,
    award: "\ud83c\udfc6 2nd Place \u00b7 Hack the Human\u2013Robot Experience",
    overview: `A companion robot that detects student emotion during solo study sessions and provides encouragement against isolation and burnout.`,
    keyFeatures: [
      `Integrated hardware systems using a LeLamp kit, Raspberry Pi, sensors, LEDs, and custom 3D-printed components, transforming a standard lamp robot into a responsive companion device.`,
      `Debugged and optimized hardware–software interaction by troubleshooting power instability, loose wiring, and faulty components through voltage testing and iterative assembly.`,
      `Achieved reliable real-time responsiveness under hackathon constraints after resolving power instability and component failures.`,
    ],
    designProcess: [
      `Adapted system architecture mid-build by incorporating Arduino components after Raspberry Pi connectivity failures, improving overall system stability.`,
      `Designed and fabricated custom 3D-printed structural and aesthetic components for the robot chassis.`,
    ],
    techUsed: ["Raspberry Pi", "Arduino", "3D Printing", "Embedded Systems", "Sensor Integration"],
    media: [
      { type: "image", src: "https://i.imgur.com/uzTcc8S.png", alt: `red lamp` },
      { type: "image", src: "https://i.imgur.com/AFc0Zrx.jpeg", alt: `red lamp` },
    ],
  },
  "planet-shafts": {
    id: "planet-shafts",
    number: "08",
    title: `Planet Shafts Redesign`,
    category: "fsae",
    categoryLabel: `Formula SAE`,
    org: `University of Toronto Formula SAE Racing`,
    date: `Feb 2026 — April 2026`,
    award: null,
    overview: `Redesigned the planet shaft component within the drivetrain's 11.97:1 compound planetary gearbox to improve manufacturability and serviceability, validating the new geometry against peak planetary-stage torque using FEA — achieving a maximum von Mises stress of 77.99 MPa with a minimum safety factor of 15 — before machining to tight tolerances. Gearbox-wide webbing optimization contributed to a 14% weight reduction (830.7 g → 711.49 g) while maintaining a predicted gearbox fatigue life of 580 hours.`,
    keyFeatures: [
      `Redesigned the planet shaft to improve assembly efficiency, manufacturability, and serviceability within the gearbox's 11.97:1 compound planetary reduction (59 sun teeth, 23/84 planet teeth).`,
      `Evaluated the shaft under peak planetary-stage torque, applying contact loads at needle-bearing interfaces with fixed supports at pin-retention features across all planet pins, using FEA to confirm a maximum von Mises stress of 77.99 MPa and a minimum safety factor of 15.`,
    ],
    designProcess: [
      `Supported gearbox-wide webbing optimization in KISSsoft that removed unnecessary material while preserving gear strength, contributing to a 14% weight reduction (830.7 g → 711.49 g) and a predicted gearbox fatigue life of 580 hours.`,
      `Machined the planet shaft within tight tolerances and ensured proper fit with mating drivetrain components during assembly.`,
    ],
    techUsed: ["SolidWorks", "ANSYS", "FEA", "Machining"],
    media: [
      { type: "image", src: "https://i.imgur.com/MBdr8uD.png", alt: `planet shaft` },
      { type: "image", src: "https://i.imgur.com/SifFkCD.png", alt: `planet shaft` },
      { type: "image", src: "https://i.imgur.com/vt1Wl1O.jpeg", alt: `planet shaft` },
    ],
  },
  "pg-marketing": {
    id: "pg-marketing",
    number: "09",
    title: `P&G Marketing Campaign`,
    category: "other",
    categoryLabel: `Hackathons & Other`,
    org: `2025 Engineering Business Future Case Competition`,
    date: `Oct 2025`,
    award: "\ud83c\udfc6 3rd Place",
    overview: `Worked in a team of four to develop a marketing strategy for Vicks Early Defense Nasal Spray, targeting increased household penetration using Porter's Five Forces and PESTLE, and delivered a clear, evidence-based presentation praised for its clarity and feasibility.`,
    keyFeatures: [
      `Worked in a group of 4 engineering students to develop a marketing campaign for Vick's Early Defense Nasal Spray, aiming to increase household penetration from 10% to 20% in a year.`,
      `Identified a key gap — a lack of exposure and reliability — and built the strategy around tackling it by using frameworks like Porter's Five Forces and PESTLE.`,
    ],
    designProcess: [
      `Delivered an evidence-based presentation that impressed judges with its clarity, feasibility, and analytical depth.`,
    ],
    techUsed: ["Marketing", "Public Speaking"],
    media: [
      { type: "image", src: "https://i.imgur.com/2ZwO3PV.png", alt: `P&G case competition` },
      { type: "image", src: "https://i.imgur.com/OIXbUgq.jpeg", alt: `P&G case competition` },
    ],
  },
  "face-tracking-robot": {
    id: "face-tracking-robot",
    number: "10",
    title: `Autonomous Face-Tracking Robot`,
    category: "other",
    categoryLabel: `Hackathons & Other`,
    org: `MakeUofT Hackathon 2026`,
    date: `Feb 2026`,
    award: null,
    overview: `Autonomous robot with real-time face detection and navigation, integrating computer vision, motor control, and a 3D-printed structure.`,
    keyFeatures: [
      `Built an autonomous robot using Raspberry Pi, OpenCV, and Arduino for real-time face detection, directional navigation, and expressive interaction.`,
      `Integrated motor control for differential drive, servo-driven head tilting for emotional expression, and dual power management (Pi + Arduino separate rails).`,
      `Implemented a smartphone-based animated face display for engaging visual feedback during interactions.`,
    ],
    designProcess: [
      `Resolved networking issues and improved face detection accuracy through iterative tuning of OpenCV parameters.`,
      `Developed both a hardware prototype and a 3D-printable robot case.`,
    ],
    techUsed: ["OpenCV", "Raspberry Pi", "Arduino", "Computer Vision", "3D Printing"],
    media: [
      { type: "image", src: "https://i.imgur.com/OUoI3R9.jpeg", alt: `face tracking robot` },
      { type: "image", src: "https://i.imgur.com/8edXN5r.png", alt: `face tracking robot` },
    ],
  },
};

